name: article_parser
description: "On-device article parser using readability_dart."
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  sanitize_html: ^2.1.0

  # Local path dep during MVP. Will be switched to git/pub before release.
  readability_dart:
    path: /Users/aizen/Projects/readability_dart

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
