name: dictionary_service
description: System and remote dictionary lookup services for Readflex.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.8
  http: ^1.6.0
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
