name: onboarding
description: 5-screen app intro shown on first launch
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  component_library:
    path: ../../component_library


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
