name: connectivity_service
description: "Reactive Stream<ConnectivityStatus> for offline detection."
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
