name: component_library
description: "UI components, theme and design tokens."
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  lucide_icons_flutter: ^3.1.14+2

flutter:
  fonts:
    - family: Geist
      fonts:
        - asset: fonts/Geist-Variable.ttf
    - family: Literata
      fonts:
        - asset: fonts/Literata-Variable.ttf
        - asset: fonts/Literata-Italic-Variable.ttf
          style: italic
    - family: PT Serif
      fonts:
        - asset: fonts/PTSerif-Regular.ttf
        - asset: fonts/PTSerif-Italic.ttf
          style: italic
        - asset: fonts/PTSerif-Bold.ttf
          weight: 700
        - asset: fonts/PTSerif-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Variable.ttf

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
